language: python
python:
 - "3.5"

# command to run tests
script:
 - python -m unittest TestTriangle

[![build status of master](https://travis-ci.org/hmigdon/triangle2HW.svg?branch=master)](https://travis-ci.org/hmigdon/triangle2HW)
